name: Flake8
on: push
jobs:
  flake8:
    name: Flake8
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8==6.1.0
      - name: Check Flake8
        run: flake8
